### ISSUE TITLE
Context empty when autocompleting after a backslash

### ISSUE THREAD

**Issue by hbragge** [sanastasiou/RTextNpp#16]
Autocomplete gives just "AUTOSAR" after a backslash (should give options for the command in the previous line).

**Comment by sanastasiou** [comment]
Need some info here, can you post file and line where you try the auto completion request?

**Comment by hbragge** [comment]
Should happen with the model_linebreak.atm you already have, for example here enter a newline after the backslash, then it tries to suggest "AUTOSAR" when you write something:
      ExclusiveArea \
        ea1
