### ISSUE TITLE
Autocompletion and highlighting wrong in a labeled child array

### ISSUE THREAD

**Issue by hbragge** [sanastasiou/RTextNpp#20]
When multiple child elements (ie. array) are assigned to a role (label), empty autocompletion options are given in the cursor position shown below (expected "CalprmElementPrototype"). Also syntax highlighting is wrong (CalprmElementPrototype colored red like an attribute).

AUTOSAR {
  ARPackage P1 {
    InternalBehavior InternalBehavior1, component: /P1/SWC1 {
      sharedCalprm: [
        |
        CalprmElementPrototype sharedCal1, type: /P1/UInt8
        CalprmElementPrototype sharedCal2, type: /P1/UInt8
      ]
    }
  }
}

request:
Info: 3:46 PM:41: [15:46:41] DEBUG request: {"context"=>["AUTOSAR {", "ARPackage P1 {", "InternalBehavior InternalBehavior1, component: /P1/SWC1 {", "      sharedCalprm: [\t  "], "column"=>25, "type"=>"request", "command"=>"content_complete", "invocation_id"=>45}

response:
Info: 3:46 PM:41: [15:46:41] DEBUG response: {"type"=>"response", "invocation_id"=>45, "options"=>[]}

**Comment by sanastasiou** [comment]
A picture would be preferable :)

**Comment by hbragge** [comment]
Kids these days.. what next, youtube video??
![labeled_child_array](https://cloud.githubusercontent.com/assets/2538226/10972915/a137550e-83db-11e5-8369-cc1251d0fa04.png)

**Comment by sanastasiou** [comment]
Haha, oh come on man :) you have my full attention. Customer support exclusively for you!

**Comment by sanastasiou** [comment]
After a massive bug fix, I am finally working on this :).. Will start with the syntax highlighting first..
