### ISSUE TITLE
No autocompletion when square bracket after linebreak

### ISSUE THREAD

**Issue by hbragge** [sanastasiou/RTextNpp#31]
Noticed that no autocompletion options appear when adding a linebreak (and newline) between the child label and opening square bracket (see screenshot). With argument arrays and opening braces this is no problem.

By the way I can't see the request/response in the debug output anymore with v0.7.258, probably because this is a release build or?

![square_bracket_after_backslash](https://cloud.githubusercontent.com/assets/2538226/11419411/42d30b0a-9427-11e5-86ac-f34c85c1032b.png)

**Comment by sanastasiou** [comment]
You can't see the request because there isn't any being made :) which is in turn of course causing the bug...

**Comment by sanastasiou** [comment]
I'll have a look at this..
