### ISSUE TITLE
NPPN_DOCORDERCHANGED wrong value

### ISSUE THREAD

**Issue by dail8859** [sanastasiou/RTextNpp#38]
Could [this](https://github.com/sanastasiou/RTextNpp/blob/master/RTextNpp/DllExport/NppPluginNETHelper.cs#L577) be the reason you're not able to catch `NPPN_DOCORDERCHANGED`? It has the same value as `NPPN_READONLYCHANGED`

In the [Notepad++ source code](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/48e9b84bb2215fb77d53f5bef10f965bef2043f1/PowerEditor/src/MISC/PluginsManager/Notepad_plus_msgs.h#L543) it is defined as `NPPN_FIRST + 17`.

**Comment by sanastasiou** [comment]
But you can't catch it either right ?

**Comment by sanastasiou** [comment]
Haha I just realised you opened a bug :) thanks.. I'll have a look at it asap.

**Comment by dail8859** [comment]
FYI, I still think there is a problem within Notepad++ (moving docs between views, opening/closing), but at least this looks like your plugin would *never* be able to catch it. :)

**Comment by sanastasiou** [comment]
Exactly. So both have a bug  :D.. I have to write some script to generate these enums out of Npp.. Who knows what will change and when.

**Comment by sanastasiou** [comment]
Synced.
